- You are using the blank identifier (`_`) to ignore the error value returned from `Square`. That's a code smell in Go. If a function returns an error value, you must check it. Right now, it may be impossible for `Square` to be called in a way that would return an error. But real code lives a long time, and undergoes many changes. At some point in the future, the implementation for `Square` could change to return different errors, or the loop code that calls `Square` could have a bug introduced which causes an error. To protect against such situations, it's wise to get into the habit of always checking your error returns.

(What should you do if the error is not `nil`? It depends on the situation. Sometimes you should pass the error back to the caller, other times you may be able to recover from the error and continue. In this case, there must be an internal error in your package, and so it's probably best to call `panic()`, which generally indicates an unrecoverable internal error.)
